package app.lightmove.api.core.security.token;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.util.Base64;
import java.util.HexFormat;

/**
 * Mints and hashes the opaque tokens: generated by {@link SecureRandom}, never a predictable RNG, and
 * stored only as SHA-256. Not BCrypt: 256 bits from a CSPRNG leave nothing to guess, so slowness would
 * buy no security and cost every refresh.
 */
public final class Tokens {

    private static final SecureRandom RANDOM = new SecureRandom();
    private static final int TOKEN_BYTES = 32; // 256 bits

    private Tokens() {
    }

    /** A URL-safe token, unpadded so it survives being pasted into an email client. */
    public static String generate() {
        byte[] bytes = new byte[TOKEN_BYTES];
        RANDOM.nextBytes(bytes);
        return Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);
    }

    /** 64 hex characters — matches the {@code varchar(64)} the token_hash columns declare. */
    public static String hash(String token) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hashed = digest.digest(token.getBytes(StandardCharsets.UTF_8));
            return HexFormat.of().formatHex(hashed);
        } catch (NoSuchAlgorithmException ex) {
            // SHA-256 is mandated by the JDK spec. Unreachable on any conformant JVM.
            throw new IllegalStateException("SHA-256 unavailable", ex);
        }
    }
}
