import type { SourcedExecutive, TeamPerformance } from "../features/reports/api/types";

const executive = (id: string, name: string, companyName: string, status: SourcedExecutive["status"], addedByName: string): SourcedExecutive => ({
  id,
  name,
  title: "Chief Financial Officer",
  seniority: "C-Suite",
  companyName,
  status,
  addedByName,
  addedAt: "2026-09-06T09:00:00Z",
});

/** Two researchers and a lead with a quiet month, over the last 30 days of `SAMPLE_REPORT`'s mandate. */
export const SAMPLE_TEAM_PERFORMANCE: TeamPerformance = {
  from: "2026-08-10",
  to: "2026-09-08",
  days: 30,
  truncated: false,
  kpis: {
    executivesInRange: 40,
    rangePerWeek: 9.3,
    mandatePerWeek: 11.6,
    coveredCompanies: 31,
    targetCompanies: 42,
    lastAddedAt: "2026-09-06T09:00:00Z",
    lastAddedBy: "Yara Haddad",
  },
  coverage: [
    { userId: "u-yara", name: "Yara Haddad", companies: 19 },
    { userId: "u-omar", name: "Omar Khoury", companies: 12 },
  ],
  researchers: [
    {
      userId: "u-yara",
      name: "Yara Haddad",
      avatarUrl: null,
      role: "LEAD",
      executives: 28,
      companies: 9,
      perDay: 0.9,
      sharePct: 70,
      lastAddedAt: "2026-09-06T09:00:00Z",
      quality: { contactPct: 64, verifiedPct: 40, compPct: 52, level: "GOOD" },
      statusMix: [
        { status: "identified", count: 18 },
        { status: "engaged", count: 6 },
        { status: "interested", count: 4 },
      ],
      daily: Array.from({ length: 30 }, (_, day) => (day % 3 === 0 ? 2 : 0)),
      recent: [executive("e1", "Amira Haddad", "Al Naboodah Group", "interested", "Yara Haddad")],
    },
    {
      userId: "u-omar",
      name: "Omar Khoury",
      avatarUrl: null,
      role: "RESEARCHER",
      executives: 12,
      companies: 5,
      perDay: 0.4,
      sharePct: 30,
      lastAddedAt: "2026-09-01T09:00:00Z",
      quality: { contactPct: 20, verifiedPct: 0, compPct: 10, level: "ATTENTION" },
      statusMix: [{ status: "identified", count: 12 }],
      daily: Array.from({ length: 30 }, (_, day) => (day % 5 === 0 ? 1 : 0)),
      recent: [executive("e2", "Nadia Salloum", "GMG", "identified", "Omar Khoury")],
    },
  ],
  companies: [
    {
      triageCompanyId: "c1",
      name: "Al Naboodah Group",
      industry: "Conglomerates",
      city: "Dubai",
      country: "United Arab Emirates",
      employees: 12000,
      stage: "inUniverse",
      executives: 3,
      contributors: 2,
      lastAddedAt: "2026-09-06T09:00:00Z",
      statusMix: [{ status: "interested", count: 1 }, { status: "identified", count: 2 }],
      quality: { contactPct: 67, verifiedPct: 33, compPct: 33, level: "ATTENTION" },
      mappedExecutives: [
        executive("e1", "Amira Haddad", "Al Naboodah Group", "interested", "Yara Haddad"),
        executive("e3", "Rami Khoury", "Al Naboodah Group", "identified", "Omar Khoury"),
      ],
    },
  ],
  companiesTotal: 31,
};
