/**
 * The two hosts the extension can be built against.
 *
 * The values live here once, and only the *choice* between them is expressed twice — by
 * `manifest.config.ts` at build time, where the mode is a build flag, and by `workspaceOrigin.ts` at
 * runtime, where it is `import.meta.env.PROD`. That split is unavoidable: the manifest is generated by
 * Node before the bundle exists. Keeping the strings in one file is what stops the code calling a host
 * the manifest never permitted, which fails as an opaque network error with nothing in the console to
 * explain it.
 */
export const PRODUCTION_WORKSPACE_ORIGIN = "https://app.lightmove.io";

/**
 * The Vite dev server, not the API on :8080 — it proxies `/api` to the API, so a development build
 * talks to exactly the origin the web app does.
 */
export const DEVELOPMENT_WORKSPACE_ORIGIN = "http://localhost:5173";
