-- One spelling per industry in the columns a mandate's own rows carry.
--
-- The company universe publishes LinkedIn's legacy V1 vocabulary, lower-cased with "and" written
-- "&". Bright Data answers in LinkedIn's V2 vocabulary, and a spreadsheet or a typed row carries
-- whatever somebody wrote. Until now the industry column took all three: the Strategy filter runs
-- `lower(industry) IN (:industries)` against a vocabulary that has no "software development", and
-- the report groups the raw column case-sensitively, so "Financial Services" and "financial
-- services" are two sectors competing for the same six slots — rendered identically, because the
-- heatmap capitalises its axis.
--
-- `Industries` now canonicalises at every door, so this is the one-off catch-up for rows written
-- before it existed. The spellings below are a snapshot of data/industry-map.json, the way V50
-- snapshotted the country catalog and V42 the template library: the map stays the authority from
-- here, and a migration is immutable.
--
-- Matched on the map's own fold — lower-cased, "and" read as "&", every separator dropped — so one
-- row covers each spelling's case and punctuation variants too. The fold here does not strip
-- diacritics as the Java one does; neither vocabulary carries any, so nothing resolvable is missed.
--
-- One statement, and deliberately no temp table: `harden.sql` revokes ALL on the database from
-- PUBLIC, which takes the TEMPORARY privilege with it, and nothing grants it back to lm_migrate. A
-- temp table here would pass every local run — Testcontainers connects as a superuser — and fail the
-- deploy step that runs migrations in production. A data-modifying CTE needs no privilege at all.
--
-- A row whose industry the map does not carry is left exactly as it is: an unresolvable spelling is
-- a fact somebody entered, not a row to guess at.

WITH spelling (folded, canonical) AS (VALUES
    ('abrasivesnonmetallicmineralsmanufacturing', 'glass, ceramics & concrete'),
    ('accessiblearchitecturedesign', 'architecture & planning'),
    ('accessiblehardwaremanufacturing', 'computer hardware'),
    ('accommodationservices', 'hospitality'),
    ('accounting', 'accounting'),
    ('administrationofjustice', 'judiciary'),
    ('administrativesupportservices', 'facilities services'),
    ('advertisingservices', 'marketing & advertising'),
    ('agriculturalchemicalmanufacturing', 'chemicals'),
    ('agriculture', 'agriculture'),
    ('agricultureconstructionminingmachinerymanufacturing', 'machinery'),
    ('airlinesaviation', 'airlines/aviation'),
    ('airwaterwasteprogrammanagement', 'government administration'),
    ('alternativedisputeresolution', 'alternative dispute resolution'),
    ('alternativefuelvehiclemanufacturing', 'automotive'),
    ('alternativemedicine', 'alternative medicine'),
    ('ambulanceservices', 'medical practice'),
    ('amusementparksarcades', 'recreational facilities & services'),
    ('animalfeedmanufacturing', 'food production'),
    ('animation', 'animation'),
    ('animationpostproduction', 'animation'),
    ('apparelfashion', 'apparel & fashion'),
    ('apparelmanufacturing', 'apparel & fashion'),
    ('applianceselectricalelectronicsmanufacturing', 'electrical/electronic manufacturing'),
    ('architecturalstructuralmetalmanufacturing', 'mining & metals'),
    ('architectureplanning', 'architecture & planning'),
    ('armedforces', 'military'),
    ('artificialrubbersyntheticfibermanufacturing', 'chemicals'),
    ('artistswriters', 'fine art'),
    ('artscrafts', 'arts & crafts'),
    ('audiovideoequipmentmanufacturing', 'consumer electronics'),
    ('automationmachinerymanufacturing', 'industrial automation'),
    ('automotive', 'automotive'),
    ('aviationaerospace', 'aviation & aerospace'),
    ('aviationaerospacecomponentmanufacturing', 'aviation & aerospace'),
    ('bakedgoodsmanufacturing', 'food production'),
    ('banking', 'banking'),
    ('barstavernsnightclubs', 'food & beverages'),
    ('bedandbreakfastshostelshomestays', 'hospitality'),
    ('beveragemanufacturing', 'wine & spirits'),
    ('biomasselectricpowergeneration', 'utilities'),
    ('biotechnology', 'biotechnology'),
    ('biotechnologyresearch', 'biotechnology'),
    ('blockchainservices', 'internet'),
    ('blogs', 'internet'),
    ('boilerstanksshippingcontainermanufacturing', 'mining & metals'),
    ('bookperiodicalpublishing', 'publishing'),
    ('bookpublishing', 'publishing'),
    ('breweries', 'wine & spirits'),
    ('broadcastmedia', 'broadcast media'),
    ('broadcastmediaproductiondistribution', 'broadcast media'),
    ('buildingconstruction', 'construction'),
    ('buildingequipmentcontractors', 'construction'),
    ('buildingfinishingcontractors', 'construction'),
    ('buildingmaterials', 'building materials'),
    ('buildingstructureexteriorcontractors', 'construction'),
    ('businessconsultingservices', 'management consulting'),
    ('businesscontent', 'information services'),
    ('businessintelligenceplatforms', 'internet'),
    ('businesssuppliesequipment', 'business supplies & equipment'),
    ('cablesatelliteprogramming', 'broadcast media'),
    ('capitalmarkets', 'capital markets'),
    ('caterers', 'food & beverages'),
    ('chemicalmanufacturing', 'chemicals'),
    ('chemicalrawmaterialsmanufacturing', 'chemicals'),
    ('chemicals', 'chemicals'),
    ('childdaycareservices', 'individual & family services'),
    ('chiropractors', 'medical practice'),
    ('circusesmagicshows', 'entertainment'),
    ('civicsocialorganization', 'civic & social organization'),
    ('civicsocialorganizations', 'civic & social organization'),
    ('civilengineering', 'civil engineering'),
    ('claimsadjustingactuarialservices', 'insurance'),
    ('clayrefractoryproductsmanufacturing', 'glass, ceramics & concrete'),
    ('climatedataanalytics', 'internet'),
    ('climatetechnologyproductmanufacturing', 'renewables & environment'),
    ('coalmining', 'mining & metals'),
    ('collectionagencies', 'financial services'),
    ('commercialindustrialequipmentrental', 'machinery'),
    ('commercialindustrialmachinerymaintenance', 'consumer services'),
    ('commercialrealestate', 'commercial real estate'),
    ('commercialserviceindustrymachinerymanufacturing', 'machinery'),
    ('communicationsequipmentmanufacturing', 'consumer electronics'),
    ('communitydevelopmenturbanplanning', 'government administration'),
    ('communityservices', 'individual & family services'),
    ('computergames', 'computer games'),
    ('computerhardware', 'computer hardware'),
    ('computerhardwaremanufacturing', 'computer hardware'),
    ('computernetworking', 'computer networking'),
    ('computernetworkingproducts', 'computer networking'),
    ('computernetworksecurity', 'computer & network security'),
    ('computerselectronicsmanufacturing', 'consumer electronics'),
    ('computersoftware', 'computer software'),
    ('conservationprograms', 'government administration'),
    ('construction', 'construction'),
    ('constructionhardwaremanufacturing', 'mining & metals'),
    ('consumerelectronics', 'consumer electronics'),
    ('consumergoods', 'consumer goods'),
    ('consumergoodsrental', 'consumer services'),
    ('consumerservices', 'consumer services'),
    ('correctionalinstitutions', 'judiciary'),
    ('cosmetics', 'cosmetics'),
    ('cosmetologybarberschools', 'education management'),
    ('courtsoflaw', 'judiciary'),
    ('creditintermediation', 'financial services'),
    ('cutleryhandtoolmanufacturing', 'mining & metals'),
    ('dairy', 'dairy'),
    ('dairyproductmanufacturing', 'dairy'),
    ('dancecompanies', 'entertainment'),
    ('datainfrastructureanalytics', 'internet'),
    ('datasecuritysoftwareproducts', 'computer software'),
    ('defensespace', 'defense & space'),
    ('defensespacemanufacturing', 'defense & space'),
    ('dentists', 'medical practice'),
    ('design', 'design'),
    ('designservices', 'design'),
    ('desktopcomputingsoftwareproducts', 'computer software'),
    ('digitalaccessibilityservices', 'information technology & services'),
    ('distilleries', 'wine & spirits'),
    ('economicprograms', 'government administration'),
    ('education', 'education management'),
    ('educationadministrationprograms', 'education management'),
    ('educationmanagement', 'education management'),
    ('elearning', 'e-learning'),
    ('elearningproviders', 'e-learning'),
    ('electricalelectronicmanufacturing', 'electrical/electronic manufacturing'),
    ('electricalequipmentmanufacturing', 'electrical/electronic manufacturing'),
    ('electriclightingequipmentmanufacturing', 'electrical/electronic manufacturing'),
    ('electricpowergeneration', 'utilities'),
    ('electricpowertransmissioncontroldistribution', 'utilities'),
    ('electronicprecisionequipmentmaintenance', 'consumer services'),
    ('embeddedsoftwareproducts', 'computer software'),
    ('emergencyreliefservices', 'individual & family services'),
    ('engineeringservices', 'mechanical or industrial engineering'),
    ('enginespowertransmissionequipmentmanufacturing', 'machinery'),
    ('entertainment', 'entertainment'),
    ('entertainmentproviders', 'entertainment'),
    ('environmentalqualityprograms', 'government administration'),
    ('environmentalservices', 'environmental services'),
    ('equipmentrentalservices', 'machinery'),
    ('eventsservices', 'events services'),
    ('executiveoffice', 'executive office'),
    ('executiveoffices', 'executive office'),
    ('executivesearchservices', 'staffing & recruiting'),
    ('fabricatedmetalproducts', 'mining & metals'),
    ('facilitiesservices', 'facilities services'),
    ('familyplanningcenters', 'medical practice'),
    ('farming', 'farming'),
    ('farmingranchingforestry', 'farming'),
    ('fashionaccessoriesmanufacturing', 'apparel & fashion'),
    ('financialservices', 'financial services'),
    ('fineart', 'fine art'),
    ('fineartsschools', 'education management'),
    ('fireprotection', 'judiciary'),
    ('fisheries', 'fishery'),
    ('fishery', 'fishery'),
    ('flighttraining', 'professional training & coaching'),
    ('foodbeveragemanufacturing', 'food production'),
    ('foodbeverageretail', 'retail'),
    ('foodbeverages', 'food & beverages'),
    ('foodbeverageservices', 'food & beverages'),
    ('foodproduction', 'food production'),
    ('footwearleathergoodsrepair', 'consumer services'),
    ('footwearmanufacturing', 'apparel & fashion'),
    ('forestrylogging', 'paper & forest products'),
    ('fossilfuelelectricpowergeneration', 'utilities'),
    ('freightpackagetransportation', 'package/freight delivery'),
    ('fruitvegetablepreservesmanufacturing', 'food production'),
    ('fuelcellmanufacturing', 'electrical/electronic manufacturing'),
    ('fundraising', 'fund-raising'),
    ('fundstrusts', 'financial services'),
    ('furniture', 'furniture'),
    ('furniturehomefurnishingsmanufacturing', 'furniture'),
    ('gamblingcasinos', 'gambling & casinos'),
    ('gamblingfacilitiescasinos', 'gambling & casinos'),
    ('geothermalelectricpowergeneration', 'utilities'),
    ('glassceramicsconcrete', 'glass, ceramics & concrete'),
    ('glassceramicsconcretemanufacturing', 'glass, ceramics & concrete'),
    ('glassproductmanufacturing', 'glass, ceramics & concrete'),
    ('golfcoursescountryclubs', 'recreational facilities & services'),
    ('governmentadministration', 'government administration'),
    ('governmentrelations', 'government relations'),
    ('governmentrelationsservices', 'government relations'),
    ('graphicdesign', 'graphic design'),
    ('groundpassengertransportation', 'logistics & supply chain'),
    ('healthhumanservices', 'government administration'),
    ('healthwellnessfitness', 'health, wellness & fitness'),
    ('highereducation', 'higher education'),
    ('highwaystreetbridgeconstruction', 'civil engineering'),
    ('historicalsites', 'museums & institutions'),
    ('holdingcompanies', 'investment management'),
    ('homehealthcareservices', 'medical practice'),
    ('horticulture', 'farming'),
    ('hospitalhealthcare', 'hospital & health care'),
    ('hospitality', 'hospitality'),
    ('hospitals', 'hospital & health care'),
    ('hospitalshealthcare', 'hospital & health care'),
    ('hotelsmotels', 'hospitality'),
    ('householdappliancemanufacturing', 'electrical/electronic manufacturing'),
    ('householdinstitutionalfurnituremanufacturing', 'furniture'),
    ('householdservices', 'consumer services'),
    ('housingcommunitydevelopment', 'government administration'),
    ('housingprograms', 'government administration'),
    ('humanresources', 'human resources'),
    ('humanresourcesservices', 'human resources'),
    ('hvacrefrigerationequipmentmanufacturing', 'machinery'),
    ('hydroelectricpowergeneration', 'utilities'),
    ('importexport', 'import & export'),
    ('individualfamilyservices', 'individual & family services'),
    ('industrialautomation', 'industrial automation'),
    ('industrialmachinerymanufacturing', 'mechanical or industrial engineering'),
    ('industryassociations', 'civic & social organization'),
    ('informationservices', 'information services'),
    ('informationtechnologyservices', 'information technology & services'),
    ('insurance', 'insurance'),
    ('insuranceagenciesbrokerages', 'insurance'),
    ('insurancecarriers', 'insurance'),
    ('insuranceemployeebenefitfunds', 'financial services'),
    ('interiordesign', 'design'),
    ('internationalaffairs', 'international affairs'),
    ('internationaltradedevelopment', 'international trade & development'),
    ('internet', 'internet'),
    ('internetmarketplaceplatforms', 'internet'),
    ('internetnews', 'online media'),
    ('internetpublishing', 'information services'),
    ('interurbanruralbusservices', 'logistics & supply chain'),
    ('investmentadvice', 'capital markets'),
    ('investmentbanking', 'investment banking'),
    ('investmentmanagement', 'investment management'),
    ('itservicesitconsulting', 'information technology & services'),
    ('itsystemcustomsoftwaredevelopment', 'information technology & services'),
    ('itsystemdataservices', 'information technology & services'),
    ('itsystemdesignservices', 'information technology & services'),
    ('itsysteminstallationdisposal', 'information technology & services'),
    ('itsystemoperationsmaintenance', 'information technology & services'),
    ('itsystemtestingevaluation', 'information technology & services'),
    ('itsystemtrainingsupport', 'information technology & services'),
    ('janitorialservices', 'facilities services'),
    ('judiciary', 'judiciary'),
    ('landscapingservices', 'facilities services'),
    ('languageschools', 'education management'),
    ('laundrydrycleaningservices', 'consumer services'),
    ('lawenforcement', 'law enforcement'),
    ('lawpractice', 'law practice'),
    ('leasingnonresidentialrealestate', 'commercial real estate'),
    ('leasingresidentialrealestate', 'real estate'),
    ('leatherproductmanufacturing', 'apparel & fashion'),
    ('legalservices', 'legal services'),
    ('legislativeoffice', 'legislative office'),
    ('legislativeoffices', 'legislative office'),
    ('leisuretraveltourism', 'leisure, travel & tourism'),
    ('libraries', 'libraries'),
    ('limegypsumproductsmanufacturing', 'glass, ceramics & concrete'),
    ('loanbrokers', 'financial services'),
    ('logisticssupplychain', 'logistics & supply chain'),
    ('luxurygoodsjewelry', 'luxury goods & jewelry'),
    ('machinery', 'machinery'),
    ('machinerymanufacturing', 'machinery'),
    ('magneticopticalmediamanufacturing', 'consumer electronics'),
    ('managementconsulting', 'management consulting'),
    ('manufacturing', 'consumer goods'),
    ('maritime', 'maritime'),
    ('maritimetransportation', 'maritime'),
    ('marketingadvertising', 'marketing & advertising'),
    ('marketingservices', 'marketing & advertising'),
    ('marketresearch', 'market research'),
    ('mattressblindsmanufacturing', 'furniture'),
    ('measuringcontrolinstrumentmanufacturing', 'consumer electronics'),
    ('meatproductsmanufacturing', 'food production'),
    ('mechanicalorindustrialengineering', 'mechanical or industrial engineering'),
    ('mediaproduction', 'media production'),
    ('mediatelecommunications', 'telecommunications'),
    ('medicaldevices', 'medical devices'),
    ('medicaldiagnosticlaboratories', 'medical practice'),
    ('medicalequipmentmanufacturing', 'medical devices'),
    ('medicalpractice', 'medical practice'),
    ('medicalpractices', 'medical practice'),
    ('mentalhealthcare', 'mental health care'),
    ('metaloremining', 'mining & metals'),
    ('metaltreatments', 'mining & metals'),
    ('metalvalveballrollermanufacturing', 'mining & metals'),
    ('metalworkingmachinerymanufacturing', 'machinery'),
    ('military', 'military'),
    ('militaryinternationalaffairs', 'government administration'),
    ('mining', 'mining & metals'),
    ('miningmetals', 'mining & metals'),
    ('mobilecomputingsoftwareproducts', 'computer software'),
    ('mobilefoodservices', 'food & beverages'),
    ('mobilegamingapps', 'computer games'),
    ('motionpicturesfilm', 'motion pictures & film'),
    ('motorvehiclemanufacturing', 'automotive'),
    ('motorvehiclepartsmanufacturing', 'automotive'),
    ('moviessoundrecording', 'motion pictures & film'),
    ('moviesvideossound', 'motion pictures & film'),
    ('museums', 'museums & institutions'),
    ('museumshistoricalsiteszoos', 'museums & institutions'),
    ('museumsinstitutions', 'museums & institutions'),
    ('music', 'music'),
    ('musicians', 'music'),
    ('nanotechnology', 'nanotechnology'),
    ('nanotechnologyresearch', 'nanotechnology'),
    ('naturalgasdistribution', 'utilities'),
    ('naturalgasextraction', 'oil & energy'),
    ('newspaperpublishing', 'newspapers'),
    ('newspapers', 'newspapers'),
    ('nonmetallicmineralmining', 'mining & metals'),
    ('nonprofitorganizationmanagement', 'nonprofit organization management'),
    ('nonprofitorganizations', 'nonprofit organization management'),
    ('nonresidentialbuildingconstruction', 'construction'),
    ('nuclearelectricpowergeneration', 'utilities'),
    ('nursinghomesresidentialcarefacilities', 'hospital & health care'),
    ('officeadministration', 'facilities services'),
    ('officefurniturefixturesmanufacturing', 'furniture'),
    ('oilcoalproductmanufacturing', 'oil & energy'),
    ('oilenergy', 'oil & energy'),
    ('oilextraction', 'oil & energy'),
    ('oilgas', 'oil & energy'),
    ('oilgasmining', 'oil & energy'),
    ('onlineaudiovideomedia', 'online media'),
    ('onlinemailorderretail', 'retail'),
    ('onlinemedia', 'online media'),
    ('operationsconsulting', 'management consulting'),
    ('optometrists', 'medical practice'),
    ('outpatientcarecenters', 'medical practice'),
    ('outsourcingoffshoring', 'outsourcing/offshoring'),
    ('outsourcingoffshoringconsulting', 'outsourcing/offshoring'),
    ('packagefreightdelivery', 'package/freight delivery'),
    ('packagingcontainers', 'packaging & containers'),
    ('packagingcontainersmanufacturing', 'packaging & containers'),
    ('paintcoatingadhesivemanufacturing', 'chemicals'),
    ('paperforestproductmanufacturing', 'paper & forest products'),
    ('paperforestproducts', 'paper & forest products'),
    ('pensionfunds', 'financial services'),
    ('performingarts', 'performing arts'),
    ('performingartsspectatorsports', 'entertainment'),
    ('periodicalpublishing', 'publishing'),
    ('personalcareproductmanufacturing', 'cosmetics'),
    ('personalcareservices', 'consumer services'),
    ('personallaundryservices', 'consumer services'),
    ('petservices', 'consumer services'),
    ('pharmaceuticalmanufacturing', 'pharmaceuticals'),
    ('pharmaceuticals', 'pharmaceuticals'),
    ('philanthropicfundraisingservices', 'philanthropy'),
    ('philanthropy', 'philanthropy'),
    ('photography', 'photography'),
    ('physicaloccupationalspeechtherapists', 'medical practice'),
    ('physicians', 'medical practice'),
    ('pipelinetransportation', 'logistics & supply chain'),
    ('plastics', 'plastics'),
    ('plasticsmanufacturing', 'plastics'),
    ('plasticsrubberproductmanufacturing', 'plastics'),
    ('politicalorganization', 'political organization'),
    ('politicalorganizations', 'political organization'),
    ('postalservices', 'logistics & supply chain'),
    ('primarymetalmanufacturing', 'mining & metals'),
    ('primarysecondaryeducation', 'primary/secondary education'),
    ('printing', 'printing'),
    ('printingservices', 'printing'),
    ('professionalorganizations', 'civic & social organization'),
    ('professionalservices', 'management consulting'),
    ('professionaltrainingcoaching', 'professional training & coaching'),
    ('programdevelopment', 'program development'),
    ('publicassistanceprograms', 'government administration'),
    ('publichealth', 'government administration'),
    ('publicpolicy', 'public policy'),
    ('publicpolicyoffices', 'public policy'),
    ('publicrelationscommunications', 'public relations & communications'),
    ('publicrelationscommunicationsservices', 'public relations & communications'),
    ('publicsafety', 'public safety'),
    ('publishing', 'publishing'),
    ('racetracks', 'sports'),
    ('radiotelevisionbroadcasting', 'broadcast media'),
    ('railroadequipmentmanufacturing', 'railroad manufacture'),
    ('railroadmanufacture', 'railroad manufacture'),
    ('railtransportation', 'logistics & supply chain'),
    ('ranching', 'ranching'),
    ('ranchingfisheries', 'ranching'),
    ('realestate', 'real estate'),
    ('realestateagentsbrokers', 'real estate'),
    ('realestateequipmentrentalservices', 'real estate'),
    ('recreationalfacilities', 'recreational facilities & services'),
    ('recreationalfacilitiesservices', 'recreational facilities & services'),
    ('regenerativedesign', 'design'),
    ('religiousinstitutions', 'religious institutions'),
    ('renewableenergyequipmentmanufacturing', 'machinery'),
    ('renewableenergypowergeneration', 'utilities'),
    ('renewableenergysemiconductormanufacturing', 'renewables & environment'),
    ('renewablesenvironment', 'renewables & environment'),
    ('repairmaintenance', 'consumer services'),
    ('research', 'research'),
    ('researchservices', 'research'),
    ('residentialbuildingconstruction', 'construction'),
    ('restaurants', 'restaurants'),
    ('retail', 'retail'),
    ('retailapparelfashion', 'apparel & fashion'),
    ('retailapplianceselectricalelectronicequipment', 'retail'),
    ('retailartdealers', 'retail'),
    ('retailartsupplies', 'arts & crafts'),
    ('retailbooksprintednews', 'retail'),
    ('retailbuildingmaterialsgardenequipment', 'retail'),
    ('retailflorists', 'retail'),
    ('retailfurniturehomefurnishings', 'retail'),
    ('retailgasoline', 'retail'),
    ('retailgroceries', 'supermarkets'),
    ('retailhealthpersonalcareproducts', 'retail'),
    ('retailluxurygoodsjewelry', 'luxury goods & jewelry'),
    ('retailmotorvehicles', 'retail'),
    ('retailmusicalinstruments', 'retail'),
    ('retailofficeequipment', 'business supplies & equipment'),
    ('retailofficesuppliesgifts', 'retail'),
    ('retailpharmacies', 'retail'),
    ('retailrecyclablematerialsusedmerchandise', 'retail'),
    ('reupholsteryfurniturerepair', 'consumer services'),
    ('roboticsengineering', 'industrial automation'),
    ('robotmanufacturing', 'industrial automation'),
    ('rubberproductsmanufacturing', 'plastics'),
    ('satellitetelecommunications', 'telecommunications'),
    ('savingsinstitutions', 'financial services'),
    ('schoolemployeebusservices', 'logistics & supply chain'),
    ('seafoodproductmanufacturing', 'food production'),
    ('secretarialschools', 'education management'),
    ('securitiescommodityexchanges', 'capital markets'),
    ('securityguardspatrolservices', 'security & investigations'),
    ('securityinvestigations', 'security & investigations'),
    ('securitysystemsservices', 'security & investigations'),
    ('semiconductormanufacturing', 'semiconductors'),
    ('semiconductors', 'semiconductors'),
    ('servicesforrenewableenergy', 'renewables & environment'),
    ('servicesfortheelderlydisabled', 'individual & family services'),
    ('sheetmusicpublishing', 'motion pictures & film'),
    ('shipbuilding', 'shipbuilding'),
    ('shuttlesspecialneedstransportationservices', 'logistics & supply chain'),
    ('sightseeingtransportation', 'logistics & supply chain'),
    ('skiingfacilities', 'recreational facilities & services'),
    ('smartmetermanufacturing', 'consumer electronics'),
    ('soapcleaningproductmanufacturing', 'chemicals'),
    ('socialnetworkingplatforms', 'internet'),
    ('softwaredevelopment', 'computer software'),
    ('solarelectricpowergeneration', 'utilities'),
    ('soundrecording', 'motion pictures & film'),
    ('spaceresearchtechnology', 'government administration'),
    ('specialtytradecontractors', 'construction'),
    ('spectatorsports', 'sports'),
    ('sportinggoods', 'sporting goods'),
    ('sportinggoodsmanufacturing', 'sporting goods'),
    ('sports', 'sports'),
    ('sportsrecreationinstruction', 'professional training & coaching'),
    ('sportsteamsclubs', 'sports'),
    ('springwireproductmanufacturing', 'mining & metals'),
    ('staffingrecruiting', 'staffing & recruiting'),
    ('steamairconditioningsupply', 'utilities'),
    ('strategicmanagementservices', 'program development'),
    ('subdivisionofland', 'civil engineering'),
    ('sugarconfectioneryproductmanufacturing', 'food production'),
    ('supermarkets', 'supermarkets'),
    ('surveyingmappingservices', 'civil engineering'),
    ('taxilimousineservices', 'logistics & supply chain'),
    ('technicalvocationaltraining', 'professional training & coaching'),
    ('technologyinformationinternet', 'internet'),
    ('technologyinformationmedia', 'information technology & services'),
    ('telecommunications', 'telecommunications'),
    ('telecommunicationscarriers', 'telecommunications'),
    ('telephonecallcenters', 'outsourcing/offshoring'),
    ('temporaryhelpservices', 'staffing & recruiting'),
    ('textilemanufacturing', 'textiles'),
    ('textiles', 'textiles'),
    ('theatercompanies', 'entertainment'),
    ('thinktanks', 'think tanks'),
    ('tobacco', 'tobacco'),
    ('tobaccomanufacturing', 'tobacco'),
    ('translationlocalization', 'translation & localization'),
    ('transportationequipmentmanufacturing', 'automotive'),
    ('transportationlogisticssupplychainstorage', 'logistics & supply chain'),
    ('transportationprograms', 'government administration'),
    ('transportationtruckingrailroad', 'transportation/trucking/railroad'),
    ('travelarrangements', 'leisure, travel & tourism'),
    ('trucktransportation', 'transportation/trucking/railroad'),
    ('trustsestates', 'financial services'),
    ('turnedproductsfastenermanufacturing', 'mining & metals'),
    ('urbantransitservices', 'logistics & supply chain'),
    ('utilities', 'utilities'),
    ('utilitiesadministration', 'government administration'),
    ('utilitysystemconstruction', 'civil engineering'),
    ('vehiclerepairmaintenance', 'consumer services'),
    ('venturecapitalprivateequity', 'venture capital & private equity'),
    ('venturecapitalprivateequityprincipals', 'venture capital & private equity'),
    ('veterinary', 'veterinary'),
    ('veterinaryservices', 'veterinary'),
    ('vocationalrehabilitationservices', 'individual & family services'),
    ('warehousing', 'warehousing'),
    ('warehousingstorage', 'warehousing'),
    ('wastecollection', 'utilities'),
    ('wastetreatmentdisposal', 'utilities'),
    ('watersupplyirrigationsystems', 'utilities'),
    ('waterwastesteamairconditioningservices', 'utilities'),
    ('wellnessfitnessservices', 'health, wellness & fitness'),
    ('wholesale', 'wholesale'),
    ('wholesalealcoholicbeverages', 'wholesale'),
    ('wholesaleapparelsewingsupplies', 'wholesale'),
    ('wholesaleapplianceselectricalelectronics', 'wholesale'),
    ('wholesalebuildingmaterials', 'building materials'),
    ('wholesalechemicalalliedproducts', 'wholesale'),
    ('wholesalecomputerequipment', 'wholesale'),
    ('wholesaledrugssundries', 'wholesale'),
    ('wholesalefoodbeverage', 'wholesale'),
    ('wholesalefootwear', 'wholesale'),
    ('wholesalefurniturehomefurnishings', 'wholesale'),
    ('wholesalehardwareplumbingheatingequipment', 'wholesale'),
    ('wholesaleimportexport', 'import & export'),
    ('wholesaleluxurygoodsjewelry', 'wholesale'),
    ('wholesalemachinery', 'wholesale'),
    ('wholesalemetalsminerals', 'wholesale'),
    ('wholesalemotorvehiclesparts', 'wholesale'),
    ('wholesalepaperproducts', 'wholesale'),
    ('wholesalepetroleumpetroleumproducts', 'wholesale'),
    ('wholesalephotographyequipmentsupplies', 'wholesale'),
    ('wholesalerawfarmproducts', 'wholesale'),
    ('wholesalerecyclablematerials', 'wholesale'),
    ('windelectricpowergeneration', 'utilities'),
    ('wineries', 'wine & spirits'),
    ('winespirits', 'wine & spirits'),
    ('wireless', 'wireless'),
    ('wirelessservices', 'wireless'),
    ('womenshandbagmanufacturing', 'apparel & fashion'),
    ('woodproductmanufacturing', 'paper & forest products'),
    ('writingediting', 'writing & editing'),
    ('zoosbotanicalgardens', 'museums & institutions')
),
triaged AS (
    UPDATE app_lm_project_triage_company AS target
    SET industry = spelling.canonical
    FROM spelling
    WHERE regexp_replace(replace(lower(btrim(target.industry)), ' and ', ' & '), '[^a-z0-9]+', '', 'g')
          = spelling.folded
      AND target.industry <> spelling.canonical
    RETURNING 1
),
off_limits AS (
    UPDATE app_lm_strategy_off_limits_company AS target
    SET industry = spelling.canonical
    FROM spelling
    WHERE regexp_replace(replace(lower(btrim(target.industry)), ' and ', ' & '), '[^a-z0-9]+', '', 'g')
          = spelling.folded
      AND target.industry <> spelling.canonical
    RETURNING 1
)
SELECT count(*) FROM (
    SELECT 1 FROM triaged
    UNION ALL SELECT 1 FROM off_limits
) AS rewritten;
